### ISSUE TITLE
Variable launch speeds

### ISSUE THREAD

**Issue by s5bug** [minkcv/pinballnx#5]
As of now, there's no variability on how far you pull the plunger back, it's either not pulled back or all the way pulled back.

**Comment by minkcv** [comment]
The game currently supports this but doesn't allow much control. It depends on how long you hold down on the analog stick.  I'll make the plunger pull slower in the next version.

**Comment by minkcv** [comment]
I've released version 0.7
I hope you will find the plunger pulls slower when you point down on the analog stick
https://github.com/minkcv/pinballnx/releases/tag/0.7
