### ISSUE TITLE
Old table plans (1980/90s)

### ISSUE THREAD

**Issue by gingerbeardman** [minkcv/pinballnx#8]
Thought you might find this interesting.

https://archive.org/details/Gamest024198809/page/n82

## Largest Images
- https://ia601409.us.archive.org/BookReader/BookReaderImages.php?zip=/22/items/Gamest024198809/Gamest%20024%201988-09_jp2.zip&file=Gamest%20024%201988-09_jp2/Gamest%20024%201988-09_0082.jp2
- https://ia601409.us.archive.org/BookReader/BookReaderImages.php?zip=/22/items/Gamest024198809/Gamest%20024%201988-09_jp2.zip&file=Gamest%20024%201988-09_jp2/Gamest%20024%201988-09_0081.jp2

## Regular Images

![](https://ia601409.us.archive.org/BookReader/BookReaderImages.php?zip=/22/items/Gamest024198809/Gamest%20024%201988-09_jp2.zip&file=Gamest%20024%201988-09_jp2/Gamest%20024%201988-09_0082.jp2&scale=8&rotate=0)![](https://ia601409.us.archive.org/BookReader/BookReaderImages.php?zip=/22/items/Gamest024198809/Gamest%20024%201988-09_jp2.zip&file=Gamest%20024%201988-09_jp2/Gamest%20024%201988-09_0081.jp2&scale=8&rotate=0)

## More info
- https://www.ipdb.org/machine.cgi?id=2699
- https://en.wikipedia.org/wiki/TX-Sector
- https://www.youtube.com/watch?v=WPP8jTqqzDU

**Comment by gingerbeardman** [comment]
Another one: 

CYCLONE (Williams, 1988)
https://archive.org/details/Gamest023198808/page/n78

**Comment by minkcv** [comment]
That's awesome. Thanks for sharing.

**Comment by gingerbeardman** [comment]
Another old one 

Torpedo Alley (Data East, 1988)
https://archive.org/details/gamest0029/page/n88/mode/2up

**Comment by gingerbeardman** [comment]
Another

The Phantom of the Opera (Data East, 1990)
https://archive.org/details/gamest0046/page/91/mode/2up

**Comment by minkcv** [comment]
That seems like it might be pretty easy to make in my game.

**Comment by aismann** [comment]
> 
> 
> That seems like it might be pretty easy to make in my game.

hint: On Android there is 'PINBALL arcade' which has 'The Phantom of the Opera' as one of the free tables.  The other one is 'Ghost Busters'.

**Comment by gingerbeardman** [comment]
There are more in GAMEST, maybe one per issue, it's just that I haven't read every issue.

**Comment by minkcv** [comment]
Sadly, the archive.org links no longer work

**Comment by aismann** [comment]
https://archive.org/details/gamest0046/page/91/mode/2up

Works!

**Comment by minkcv** [comment]
Thanks, I would really like to find the TX Sector one, though.

Edit: Here it is 
https://archive.org/details/gamest0024/page/n82/mode/2up

**Comment by gingerbeardman** [comment]
Another useful site: https://www.ipdb.org

May contain plans.
