### ISSUE TITLE
YouTube video about the pinballnx functionality

### ISSUE THREAD

**Issue by aismann** [minkcv/pinballnx#9]
Hello minkcv,

I have found your pinballnx.
I want use your "graphic and ideas" to make a clone for windows and android systems.

I dont want use Box2D and all the other stuff.
Can I get it  and maybe an YouTube to see how it should work?

Thanks

**Comment by gingerbeardman** [comment]
It's pinball so if you imagine the ball and flippers moving on this screenshot you're pretty much there.

https://www.homebrewgeneral.net/2019/08/pinballnx-v07-released.html

![https://1.bp.blogspot.com/-jNoWNrdKlMI/XVM8-oYiVmI/AAAAAAAABIA/xU_HwVlBHy83Tx9lDH2FK1jlVA4b5D_YwCLcBGAs/s1600/pinballnx-switch.png](https://1.bp.blogspot.com/-jNoWNrdKlMI/XVM8-oYiVmI/AAAAAAAABIA/xU_HwVlBHy83Tx9lDH2FK1jlVA4b5D_YwCLcBGAs/s1600/pinballnx-switch.png)

**Comment by minkcv** [comment]
If you don't want to use Box2D then you're making a whole new game pretty much. I plan on releasing on Windows at some point later. The project is open source under the MIT license so you can look through the code. 

Here is a short video on it being played
https://www.twitch.tv/videos/518360709

**Comment by aismann** [comment]
Thanks! All this info is helping me.

**Comment by minkcv** [comment]
Here is a video of the released version for Windows
https://www.youtube.com/watch?v=FGZBYZOYhv4

Download for Windows
https://minkcv.itch.io/pinballnx
